receivers:
    prometheus:
      config:
        scrape_configs:
          - job_name: 'prom-col'
            scrape_interval: 5s
            static_configs:
              - targets: ['host.docker.internal:8080']
exporters:
  googlecloud:
    log:
      default_log_name: opentelemetry.io/collector-exported-log
processors:
  batch:
service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch] # NOTICE: use memory_limiter in production
      exporters: [googlecloud]
